// Code generated by goctl. DO NOT EDIT.
// Source: register.proto

package server

import (
	"context"
	"github.com/LCY2013/blockchain/exchange/ff-coin/grpc-common/ucenter/types/register"
	"github.com/LCY2013/blockchain/exchange/ff-coin/ucenter/internal/logic"
	"github.com/LCY2013/blockchain/exchange/ff-coin/ucenter/internal/svc"
)

type RegisterServer struct {
	svcCtx *svc.ServiceContext
	register.UnimplementedRegisterServer
}

func NewRegisterServer(svcCtx *svc.ServiceContext) *RegisterServer {
	return &RegisterServer{
		svcCtx: svcCtx,
	}
}

func (s *RegisterServer) RegisterByPhone(ctx context.Context, in *register.RegReq) (*register.RegRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.RegisterByPhone(in)
}
func (s *RegisterServer) SendCode(ctx context.Context, in *register.CodeReq) (*register.NoRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}